name: Build and Push Image

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: "${{ secrets.GCP_KEY }}"
          project_id: "vibradev-dev"

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/vibradev-dev/dev/hello-go:latest .

      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/vibradev-dev/dev/hello-go:latest
